### PR TITLE
refactor: restructure entire codebase

### PR DESCRIPTION
**Pull request by Ssentiago**
- Improved project structure
- Separated concerns into modules
- Added proper typing organization
- Moved diagram-related code to dedicated folders and files
- Moved panel-related code to dedicated folders and files
- Moved events-related code to dedicated folders and files
- No functional changes, only code organization

### CODE REVIEW

**Comment by Ssentiago** [comment]
@gitcpy can you check this? I rewrote the code structure (no functional changes) and tested it. 
Please help review to ensure everything works correctly.

**Comment by gitcpy** [comment]
Yes.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月19日(星期六) 晚上10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)














 
@gitcpy can you check this? I rewrote the code structure (no functional changes) and tested it.
 Please help review to ensure everything works correctly.

**Comment by Ssentiago** [comment]
> Yes.
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2024年10月19日(星期六) 晚上10:08
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> @gitcpy can you check this? I rewrote the code structure (no functional changes) and tested it.
>  Please help review to ensure everything works correctly.
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

What?

**Comment by gitcpy** [comment]
You email to me and said “can you check this?”. And I reply "Yes".&nbsp;
Is there any I have to do?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/diagram-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月19日(星期六) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)





  
Yes.
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人: @.&gt;;
 发送时间: 2024年10月19日(星期六) 晚上10:08
 收件人: @.&gt;;
 抄送: @.&gt;; @.&gt;;
 主题: Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)
 
@gitcpy can you check this? I rewrote the code structure (no functional changes) and tested it.
 Please help review to ensure everything works correctly.
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: @.***&gt;
  
What?

**Comment by Ssentiago** [comment]
7> You email to me and said “can you check this?”. And I reply "Yes".&nbsp;
> Is there any I have to do?
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "gitcpy/diagram-zoom-drag"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年10月19日(星期六) 晚上11:52
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)
> 
> 
> 
> 
> 
>   
> Yes.
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人: @.&gt;;
>  发送时间: 2024年10月19日(星期六) 晚上10:08
>  收件人: @.&gt;;
>  抄送: @.&gt;; @.&gt;;
>  主题: Re: [gitcpy/diagram-zoom-drag] refactor: restructure entire codebase (PR #33)
>  
> @gitcpy can you check this? I rewrote the code structure (no functional changes) and tested it.
>  Please help review to ensure everything works correctly.
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you were mentioned.Message ID: @.***&gt;
>   
> What?
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Yup, check it out when you can

**Pull request merged**
